****

## 异常概念

异常，就是不正常的意思。在程序中的意思是：

	- 指的是程序在执行过程中出现的非正常行为，最终会导致JVM的非正常停止。

在`Java`等面向对象的编程语言中，异常本身就是一个类，产生异常就是创建异常对象并抛出一个异常对象。`Java`处理异常的方式是中断处理。

	- 异常指的并不是语法错误，语法错误时编译不通过，不会产生字节码文件，根本不能运行。



## 异常体系

	异常机制其实是帮助我们找到程序中的问题，异常的根类是java.lang.Throwable，其下有两个子类：java.lang.Error与java.lang.Exception。

- `Error`：严重错误，无法通过处理的错误，只能事先避免，好比绝症。
- `Eeception`：表示异常，异常产生后程序员可以通过代码的方式纠正，使程序正常运行，是必须处理的。

`Throwable`中的常用方法：

- `public void printStackTrace()`：打印异常的详细信息。
	包含了异常的类型、异常的产生原因、异常出现的位置。在开发和调试阶段都的使用它。
	
- `public String getMessage()`：获取发生异常的原因。
	提示给用户的时候就提示错误原因。
	
- `public String toString()`：获取异常的类型和异常描述信息。



## 异常分类

	我们平常说的异常是指Exception，因为这类异常一旦发生我们就要对代码进行修改。

异常（`Exception`）的分类：根据在编译时期还是运行时期去检查异常。

- *编译时异常* ：`checked`异常。在编译时期就会检查，如果没有处理异常则编译失败。（如日期格式化异常）
	
- *运行时异常* ：`runtime`异常。在运行期间检查异常，在编译时期运行异常不会被编译器检测（不报错）。（如除零异常）



## 抛出异常

	在编写程序时，我们必须要考虑程序出现问题的情况。比如，在定义方法时，方法需要接受参数。那么，当调用方法使用接受到的参数时，首先需要先对参数数据进行合法的判断，数据若不合法，就应该告诉调用者，传递合法的数据进来。这时需要使用抛出异常的方式来告诉调用者。


在java中，提供了一个**throw**关键字，它用来抛出一个指定的异常对象。那么，抛出一个异常具体如何操作呢？

1. 创建一个异常对象。封装一些提示信息(信息可以自己编写)。
    
2. 需要将这个异常对象告知给调用者。怎么告知呢？怎么将这个异常对象传递到调用者处呢？通过关键字throw就可以完成。throw 异常对象。
    
    throw**用在方法内**，用来抛出一个异常对象，将这个异常对象传递到调用者处，并结束当前方法的执行。
    

**使用格式**：

```java
throw new 异常类名(参数);
```

例如：
```java
throw new NullPointerException("要访问的arr数组不存在");  
​  
throw new ArrayIndexOutOfBoundsException("该索引在数组中不存在，已超出范围");
```


学习完抛出异常的格式后，我们通过下面程序演示下throw的使用。
```java
public class ThrowDemo {  
    public static void main(String[] args) {  
        //创建一个数组   
        int[] arr = {2,4,52,2};  
        //根据索引找对应的元素   
        int index = 4;  
        int element = getElement(arr, index);  
​  
        System.out.println(element);  
        System.out.println("over");  
    }  
    /*  
     * 根据 索引找到数组中对应的元素  
     */  
    public static int getElement(int[] arr,int index){   
        //判断  索引是否越界  
        if(index<0 || index>arr.length-1){  
             /*  
             判断条件如果满足，当执行完throw抛出异常对象后，方法已经无法继续运算。  
             这时就会结束当前方法的执行，并将异常告知给调用者。这时就需要通过异常来解决。   
              */  
             throw new ArrayIndexOutOfBoundsException("哥们，角标越界了```");  
        }  
        int element = arr[index];  
        return element;  
    }  
}
```



> 注意：如果产生了问题，我们就会throw将问题描述类即异常进行抛出，也就是将问题返回给该方法的调用者。
> 
> 那么对于调用者来说，该怎么处理呢？一种是进行捕获处理，另一种就是继续讲问题声明出去，使用throws声明处理。


## 声明异常

	将问题标识出来，报告给调用者。如果方法内通过throw抛出了编译时异常，而没有捕获处理，那么必须通过throws进行声明，让调用者去处理。

	关键字throws运用于方法声明之上,用于表示当前方法不处理异常,而是提醒该方法的调用者来处理异常(抛出异常).

`throws`用于进行异常类的声明，若该方法可能有多种异常情况产生，那么在`throws`后面可以写多个异常类，用逗号隔开。

```java
public class ThrowsDemo2 {
    public static void main(String[] args) throws IOException {
        read("a.txt");
    }

    public static void read(String path)throws FileNotFoundException, IOException {
        if (!path.equals("a.txt")) {//如果不是 a.txt这个文件 
            // 我假设  如果不是 a.txt 认为 该文件不存在 是一个错误 也就是异常  throw
            throw new FileNotFoundException("文件不存在");
        }
        if (!path.equals("b.txt")) {
            throw new IOException();
        }
    }
}
```



## 捕获异常

	如果异常出现的话会终止程序，所以我们得处理异常。

处理方式：

- 该方法不处理而是声明抛出，由该方法的调用者处理（`throws`）。
	
- 在方法中使用`try-catch`的语句块来处理。


`try-catch`的方式就是捕获异常。

*捕获异常* ：`Java`中对异常有针对性的语句进行捕获，可以对出现的异常进行指定方式的处理。

捕获异常的语法如下：

```java
try{
	可能出现异常的代码
}catch(异常类型 e){
	处理异常的代码
	//记录日志/打印异常信息/继续抛出异常
}
```

> `try`和`catch`都不能单独使用，必须连用。


演示如下：
```java
public class TryCatchDemo {
    public static void main(String[] args) {
        try {// 当产生异常时，必须有处理方式。要么捕获，要么声明。
            read("b.txt");
        } catch (FileNotFoundException e) {// 括号中需要定义什么呢？
          	//try中抛出的是什么异常，在括号中就定义什么异常类型
            System.out.println(e);
        }
        System.out.println("over");
    }
    /*
     *
     * 我们 当前的这个方法中 有异常  有编译期异常
     */
    public static void read(String path) throws FileNotFoundException {
        if (!path.equals("a.txt")) {//如果不是 a.txt这个文件 
            // 我假设  如果不是 a.txt 认为 该文件不存在 是一个错误 也就是异常  throw
            throw new FileNotFoundException("文件不存在");
        }
    }
}
```

异常处理的方式可以使用`Throwable`类中的几个方法。

在开发中也可以用`catch`将编译时异常转换为运行时异常处理。

多个异常使用捕获又该如何处理呢？

1. 多个异常分别处理。
2. 多个异常一次捕获，多次处理。
3. 多个异常一次捕获

一般我们使用一次捕获多次处理方式，格式如下：

```java
try{
     编写可能会出现异常的代码
}catch(异常类型A  e){  当try中出现A类型异常,就用该catch来捕获.
     处理异常的代码
     //记录日志/打印异常信息/继续抛出异常
}catch(异常类型B  e){  当try中出现B类型异常,就用该catch来捕获.
     处理异常的代码
     //记录日志/打印异常信息/继续抛出异常
}
```

	注意:这种异常处理方式，要求多个catch中的异常不能相同，并且若catch中的多个异常之间有子父类异常的关系，那么子类异常要求在上面的catch处理，父类异常在下面的catch处理。



## `finally`代码块

**finally**：有一些特定的代码无论异常是否发生，都需要执行。另外，因为异常会引发程序跳转，导致有些语句执行不到。而`finally`就是解决这个问题的，在`finally`代码块中存放的代码都是一定会被执行的。

什么时候的代码必须最终执行？

当我们在`try`语句块中打开了一些物理资源(磁盘文件/网络连接/数据库连接等),我们都得在使用完之后,最终关闭打开的资源。

`finally`的语法:

`try...catch....finally`:自身需要处理异常,最终还得关闭资源。

> 注意:`finally`不能单独使用。

比如在我们之后学习的`IO`流中，当打开了一个关联文件的资源，最后程序不管结果如何，都需要把这个资源关闭掉。

`finally`代码参考如下：

```java
public class TryCatchDemo4 {  
    public static void main(String[] args) {  
        try {  
            read("a.txt");  
        } catch (FileNotFoundException e) {  
            //抓取到的是编译期异常  抛出去的是运行期   
            throw new RuntimeException(e);  
        } finally {  
            System.out.println("不管程序怎样，这里都将会被执行。");  
        }  
        System.out.println("over");  
    }  
    /*  
     *  
     * 我们 当前的这个方法中 有异常  有编译期异常  
     */  
    public static void read(String path) throws FileNotFoundException {  
        if (!path.equals("a.txt")) {//如果不是 a.txt这个文件   
            // 我假设  如果不是 a.txt 认为 该文件不存在 是一个错误 也就是异常  throw  
            throw new FileNotFoundException("文件不存在");  
        }  
    }  
}
```

> 当只有在try或者catch中调用退出JVM的相关方法,此时finally才不会执行,否则finally永远会执行。



## 异常注意事项

- 运行时异常被抛出可以不处理。即不捕获也不声明捕获。

- 如果父类抛出多个异常，子类覆盖父类方法是，只能抛出相同的异常或者它的子集。

- 父类方法没有抛出异常，子类覆盖父类该方法时也不可抛出异常。此时子类产生该异常，只能捕获处理，不能声明抛出。

- 当多异常处理时，捕获处理，前边的类不能是后边类的父类。

- 在`try/catch`后可以追加`finally`代码块，其中的代码一定会被执行，通常用于资源回收。


## 自定义异常

为什么需要自定义异常类？

> 我们说了`Java`中不同的异常类,分别表示着某一种具体的异常情况,那么在开发中总是有些异常情况是`SUN`没有定义好的,此时我们根据自己业务的异常情况来定义异常类。,例如年龄负数问题,考试成绩负数问题。

什么时自定义异常类？

> 在开发中根据自己业务的异常情况来定义异常类.

异常类如何定义：

> 1、自定义编译时异常：自定义类并继承于`java.lang.Exception`。
>2、自定义运行时异常：自定义类并继承于`java.lang.RuntimeException`。


演示如下：

```java
// 业务逻辑异常
public class LoginException extends Exception {
    /**
     * 空参构造
     */
    public LoginException() {
    }

    /**
     *
     * @param message 表示异常提示
     */
    public LoginException(String message) {
        super(message);
    }
}
```

模拟登陆操作，使用数组模拟数据库中存储的数据，并提供当前注册账号是否存在方法用于判断。

```java
public class Demo {
    // 模拟数据库中已存在账号
    private static String[] names = {"bill","hill","jill"};
   
    public static void main(String[] args) {     
        //调用方法
        try{
            // 可能出现异常的代码
            checkUsername("nill");
            System.out.println("注册成功");//如果没有异常就是注册成功
        } catch(LoginException e) {
            //处理异常
            e.printStackTrace();
        }
    }

    //判断当前注册账号是否存在
    //因为是编译期异常，又想调用者去处理 所以声明该异常
    public static boolean checkUsername(String uname) throws LoginException {
        for (String name : names) {
            if(name.equals(uname)){//如果名字在这里面 就抛出登陆异常
                throw new LoginException("亲"+name+"已经被注册了！");
            }
        }
        return true;
    }
}
```